=== codeaudit/cougaar-glm/glm/src/org/cougaar/mlm/ui/producers/policy/policy.dtd
<!ELEMENT LogPlan (UIPolicy)+>
<!ELEMENT UIPolicy (policyName, names+, values+, UUID)>
<!ELEMENT policyName (#PCDATA)>
<!ELEMENT UUID (#PCDATA)>
<!ELEMENT names (#PCDATA)>
<!ELEMENT values (#PCDATA)>

=== codeaudit/cougaar-glm/glm/src/org/cougaar/domain/mlm/ui/producers/policy/policy.xml
<?xml version="1.0"?>
<!DOCTYPE LogPlan SYSTEM "policy.dtd">
<LogPlan>
  <UIPolicy>
    <policyName>ShipPolicy</policyName>
    <names>ShipMode</names>
    <names>ShipDays</names>
    <values>Ground</values>
    <values>2</values>
    <UUID>1</UUID>
  </UIPolicy>
</LogPlan>
